### ISSUE TITLE
Attachment detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#105]
To completely replace the old application, attachment detail view is needed: http://geokogud.info/attachment/168

**Comment by enmust** [comment]
How do I get these relations properly?
Old code
![image](https://user-images.githubusercontent.com/14908993/39248721-83923c12-48a5-11e8-9f74-d9ae5f9d2313.png)
![image](https://user-images.githubusercontent.com/14908993/39248779-a847f8c6-48a5-11e8-8640-a6a725f4c8f8.png)

The most comfortable would be to use attachment_link table directly from attachment table so I could get all relations using one request. 
for example: https://api.geocollections.info/attachment/168?fields=attachmentlink__sample__id,attachmentlink__sample__number

I think the second way which I could do right now would be calling a new request with attachment_id using attachment_link table.

I noticed attachment table has link_id and link_table fields but these do not help me much because sometimes there can be more than one relation for example: http://geokogud.info/attachment/168

**Comment by enmust** [comment]
Done
