### ISSUE TITLE
Detail page styling

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#13]
Detail view pages have several common problems: 
* Padding and borders should the same for all pages (compare: http://arendus.geokogud.info/specimen/275271 and http://arendus.geokogud.info/locality/15130)
* Unnecessary borders should be removed
* Subform main font size should be smaller
* Subform headings should be and look as headings (currently label tag is used)
* All table headers should have background-color to differentiate from data cells, as in main page search results table.
* Pages look ugly when opened in full screen window (which happens if the page is opened using link from external application), the header box remains small (open in full screen window: http://arendus.geokogud.info/stratigraphy/659), there is lot of empty space (maybe set max-width for tables); 
* sometimes floating of elements does not work as expected, check map in http://arendus.geokogud.info/locality/12337
* page header-footer question are filed as a separate issue

**Comment by enmust** [comment]
- ~~Padding and borders should the same for all pages (compare: http://arendus.geokogud.info/specimen/275271 and http://arendus.geokogud.info/locality/15130)~~

- Unnecessary borders should be removed

- Subform main font size should be smaller

- Subform headings should be and look as headings (currently label tag is used)

- All table headers should have background-color to differentiate from data cells, as in main page search results table.

- Pages look ugly when opened in full screen window (which happens if the page is opened using link from external application), the header box remains small (open in full screen window: http://arendus.geokogud.info/stratigraphy/659), there is lot of empty space (maybe set max-width for tables);

- ~~sometimes floating of elements does not work as expected, check map in http://arendus.geokogud.info/locality/12337~~

- page header-footer question are filed as a separate issue
