### ISSUE TITLE
Autocomplete fields in search filters too slow

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#19]
Autocomplete combo boxes in extended search filters are too slow (e.g. fossil name, stratigraphy etc) as  source data are requested from related tables. This is a feature to ensure that there are matching records  in the database and thus at least some search results can be returned. It would be much quicker to feed the autocompletes directly from the source tables (taxon, stratigraphy etc). In that way the autocomplete search fields may return no results, but UI responsiveness is more important. And user may specify additional criteria anyway that end up with no search results.
Alternative solution would be to have temporary tables that hold e.g., locality_specimen would hold list of all localities that have related specimens etc.

**Comment by enmust** [comment]
In some cases when it took too long I changed autocomplete to take info directly from source tables. 
Also in some cases the difference was only 100ms, for example autocomplete took 40ms to get from source table but 140ms to get a matching record, so I left the matching autocomplete in, because user couldn't see noticeable difference.
