### ISSUE TITLE
Front page components

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#26]
Three brief articles should remain as they are, perhaps the red icons should be inside text boxes. 
However, all texts should be updated, number of database records made more general etc. 
If the three text boxes are placed vertically (browser window less than 990px) the boxes should become wider -- why not as wide as the articles in gray area below. The header menu should be adjusted accordingly.

Articles/tabs on grey background should be in the following order: News, Using collections, About, Database, GIT, TUG, ELM. So that the news are displayed on front page.
A better solution is needed for titles of these articles, for instance About collections tab shows two almost same headings: Geological collections in Estonia, About geological collections in Estonia. An easy solution would be to remove heading from the article in database. 
Another useful feature would be the possibility to link to specific page or specific news item using url. For instance, to use in FB post or something alike.

**Comment by enmust** [comment]
Three brief articles should remain as they are, perhaps the red icons should be inside text boxes.
However, all texts should be updated, number of database records made more general etc.
~~If the three text boxes are placed vertically (browser window less than 990px) the boxes should become wider -- why not as wide as the articles in gray area below.~~ The header menu should be adjusted accordingly.

~~Articles/tabs on grey background should be in the following order: News, Using collections, About, Database, GIT, TUG, ELM. So that the news are displayed on front page.~~
A better solution is needed for titles of these articles, for instance About collections tab shows two almost same headings: Geological collections in Estonia, About geological collections in Estonia. An easy solution would be to remove heading from the article in database.
Another useful feature would be the possibility to link to specific page or specific news item using url. For instance, to use in FB post or something alike.

**Comment by enmust** [comment]
Closed this issue because it was too broad, made new issues instead.
