### ISSUE TITLE
specimen table view wrong image url

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#49]
Table view of specimens creates image url with wrong institution acronym, perhaps 'git' is hardcoded instead of coming from data: http://arendus.geokogud.info/specimen?specimen_number_1=5&specimen_number=10-6&collection_id_1=5&collection_id=&classification_1=1&classification=&taxon_1=1&taxon=&name_geology_1=1&name_geology=&country_1=1&country=&locality_1=1&locality=&stratigraphy_1=1&stratigraphy=&id_1=5&id=&fossil_1=1&fossil=&agent_1=1&agent=&reference_1=1&reference=&original_type_1=1&original_type=&part_1=1&part=&tags_1=1&tags=&dbs%5B%5D=1&dbs%5B%5D=2&dbs%5B%5D=3&dbs%5B%5D=4&dbs%5B%5D=5&dbs%5B%5D=6&currentTable=specimen&maxSize=5&sort=id&sortdir=DESC

**Comment by ollehints** [comment]
solr index now has fields image_url and image_preview_url

**Comment by enmust** [comment]
'Git' is not hardcoded but somehow specimen_image_thumbnail field gets injected into wrong place. 
![image](https://user-images.githubusercontent.com/14908993/34070992-be4f5afe-e277-11e7-9009-9f00b404798d.png)
Specimen_image_thumbnail count should be 0
Probably some bug in the java side which needs investigation

**Comment by enmust** [comment]
Fixed the bug. 
Problem was that it took specimen_id from specimen table and specimen__specimen_id from specimen_image table.
Changed it to take id from specimen table and specimen_id from specimen_image. Bug appeared because specimen_id was 10-6 on both cases.
Now it should be fine.
![image](https://user-images.githubusercontent.com/14908993/34071177-17984384-e27b-11e7-8d18-4195ecdf6360.png)
