### ISSUE TITLE
Autocomplete fields

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#50]
Some autocomplete fields use wrong fieldname to search data. Here should come each table view search fields which should be autocompleted and which fieldname should they use when searching from API. 
@ollehints

**Comment by ollehints** [comment]
## Specimen
* **specimen number** contains : specimen_id OR specimen_nr (would it be feasible to remove collections acronym from this field so that user will get some matches even if searching for long number, for instance "TUG" and "TUG " will be removed from user input).
* **collection number** contains : coll__number (OR query not necessary)
* classification -- remove this field as all specimens should have some identification related to rock hierarchy or fossil taxonomy
* **fossil name** contains : autocomplete taxon__taxon, search specimenidentification__taxon__taxon OR specimenidentification__name; search option should include 'hierarchy', then name and all its children will be searched (API call like this: https://api.arendus.geokogud.info/specimen/?format=json&specimenidentification__taxon__taxon__exact__hierarchy=Ramphoprion)
* **mineral and rock name** contains : autocomplete rock__name/rock_name_en, search specimenidentificationgeologies__rock__name OR specimenidentificationgeologies__rock__name_en OR specimenidentificationgeologies__name; in the future hierarchy search needs to be implemented
* **locality** contains : autocomplete locality__locality/locality_en, search locality_free OR locality__locality_en OR locality__locality
* **country/county/parish** (instead of admin unit) : search from locality__country__value OR locality__country__value_en OR locality__asustusyksus__asustusyksus OR locality__asustusyksus__asustusyksus_en OR locality__vald__vald OR locality__vald__vald_en OR locality__maakond__maakond OR locality__maakond__maakond_en
* **stratigraphy** contains : autocomplete stratigraphy__stratigraphy/stratigraphy_en, search stratigraphy__stratigraphy OR stratigraphy__stratigraphy OR lithostratigraphy__stratigraphy OR lithostratigraphy__stratigraphy_en OR stratigraphy_free
### additional criteria
* **ID** equals : search id
* **Fossil/Mineral/Rock** : remove, will return once switching to solr
* **Depth interval** : search depth>depth AND depth<depth
* **Collector contains** : autocomplete agent__agent, search agent_collected__agent OR agent_free 
* **Reference contains** : autocomplete reference__reference, search specimenreference__reference__reference OR specimenreference__reference__author OR specimenreference__reference__title
* **Type status** contains : lookup original_status__value/value_en, search original_status__value OR 
original_status__value_en
* **Part contains** : search part
* **Key words** contains: search tags
* **Reg. date** interval: date_added>X AND date_added<X
