### ISSUE TITLE
Reference search

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#78]
Ursula reported: 
Reference search fields should include: 
* abstract 
* keywords
Author, title and book should not be autocomplete fields (the current behaviour does not speed up searching as too many irrelevant options are usually offered to the user).

**Comment by enmust** [comment]
Added abstract search field and removed autocomplete from author, title and book. 

Should user find references using keywords? If yes then should I use reference_keyword table because reference table does not contain keyword field.

**Comment by enmust** [comment]
Added keywords search field.

It is searching references under 'tags' field in reference table because I couldn't add reference_keyword table to API. I tried adding it to config.py but it gave me an error: **AttributeError at /reference_keyword/
'module' object has no attribute 'ReferenceKeyword'** . 

I also checked that reference table has 800 results for 'tags' which are not null or empty.

**Comment by ollehints** [comment]
API now works for reference_keyword__keyword search:
https://api.arendus.geokogud.info/reference/?referencekeywords__keyword__icontains=chitinozoa

**Comment by enmust** [comment]
Changed tags to referencekeywords__keyword
