### ISSUE TITLE
Is it possible to add locality_summary table to Apache Solr

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#92]
Approx 10k results from API takes 2-3 sec

**Comment by ollehints** [comment]
Added field **total_related_records** to solr locality index, so there is no need to add locality_summary index separately. field names aredifferent though, e.g., related_specimens inspead of specimens, related_drillcores instead of drillcores etc. Should work for a bit faster map data retrieval: http://193.40.102.11:8983/solr/locality/select?q=*:*&rows=10000&fl=longitude,latitude,id,locality,total_related_records takes ca 0.4-1 s

**Comment by enmust** [comment]
Map now uses Solr
